Pages/Admin/Login.cshtml.cs
using Lombok.NET;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PRN221_Assignment.ExtenModel;
using PRN221_Assignment.Services.Interface;
using System.Security.Claims;

namespace PRN221_Assignment.Pages.Admin
{
    [RequiredArgsConstructor]
    public partial class LoginAdminModel : PageModel
    {
        [BindProperty]
        public ExtenModel.Admin? User { get; set; } = default!;
        private readonly ILoginService _loginService;
        private readonly ILogger<LoginAdminModel> _logger;
        public string error;

        public void OnGet()
        {

        }
        public IActionResult OnPost()
        {
            var userLogin = _loginService.ExistUserAdmin(User.Username, User.Key);

            if (userLogin != null)
            {
                List<Claim> listClaim = new List<Claim>()
            {
                new Claim(ClaimTypes.Name, userLogin.Username),
                new Claim(ClaimTypes.NameIdentifier, userLogin.Id),
                new Claim(ClaimTypes.Role, "Admin"),
                new Claim(ClaimTypes.GivenName, userLogin.Id),
                new Claim("profile_picture","./assets/images/user/null.png")
                 };
                ClaimsIdentity ci = new ClaimsIdentity(listClaim, Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationDefaults.AuthenticationScheme);
                ClaimsPrincipal cp = new ClaimsPrincipal(ci);
                HttpContext.SignInAsync(cp);
                return RedirectToPage("/Admin/HomePage");
            }
            error = "Username or password is incorrect!";
            return Page();
        }
        
        public async Task<IActionResult> OnGetLogout()
        {
            await HttpContext.SignOutAsync(Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToPage("/Login");
        }
    }
}

Pages/EditPost.cshtml.cs
using Lombok.NET;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PRN221_Assignment.Models;
using PRN221_Assignment.Services;
using PRN221_Assignment.Services.Interface;
using System.IO;
using System.Linq;

namespace PRN221_Assignment.Pages
{
    [Authorize(Roles = "User")]
    [RequiredArgsConstructor]

    public partial class EditPostModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public int PostId { get; set; }
        public Post post { get; set; }
        private readonly IPostService _postService;
        private readonly IPhotoService _photoService;

        public IActionResult OnGet(int PostId)
        {
            ViewData["post"] = _postService.GetPostById(PostId);
            ViewData["photo"] = _photoService.GetPhotosById(PostId);

            return Page();
        }
        
        public async Task<IActionResult> OnPost(Post post, string imageNames, List<IFormFile> listfile)
        {
            ViewData["post"] = _postService.GetPostById(post.PostId);
            ViewData["photo"] = _photoService.GetPhotosById(post.PostId);
            var listphoto = _photoService.GetPhotosById(post.PostId);
            var listPhotoName = new List<string>();

            if (imageNames != null && listphoto.Count != 0)
            {
                var listPhotoUrlExist = imageNames.Split("||");
                //_photoService.DeletePhoto(post.PostId);
                foreach (var photoUrlDb in listphoto)
                {
                    var a = listPhotoUrlExist.Contains(photoUrlDb.PhotoUrl);
                    if (a)
                    {
                        listPhotoName.Add(photoUrlDb.PhotoUrl.Split('/').Last());
                    }
                    else
                    {
                        var nameFile = photoUrlDb.PhotoUrl.Split('/').Last();
                        string filePathExist = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Image/UploadPic", nameFile);
                        if (System.IO.File.Exists(filePathExist))
                        {
                            System.IO.File.Delete(filePathExist);
                        }
                    }
                }
            }
            else if (imageNames == null && listphoto.Count != 0)
            {
                foreach (var photo in listphoto)
                {
                    var name = photo.PhotoUrl.Split('/').Last();
                    string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Image/UploadPic", name);
                    if (System.IO.File.Exists(filePath))
                    {
                        System.IO.File.Delete(filePath);
                    }
                }
            }

            if (listfile.Count != 0)
            {
                foreach (var file in listfile)
                {
                    if (file.Length > 0)
                    {
                        string fileExtension = Path.GetExtension(file.FileName);
                        string fileNameWithoutExtension = Path.GetFileNameWithoutExtension(file.FileName);
                        string directory = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Image/UploadPic");
                        string filePath1 = Path.Combine(directory, file.FileName);
                        int index = 1;

                        
                        if (!Directory.Exists(directory))
                        {
                            Directory.CreateDirectory(directory);
                        }

                        
                        while (System.IO.File.Exists(filePath1))
                        {
                            filePath1 = Path.Combine(directory, fileNameWithoutExtension + "(" + index + ")" + fileExtension);
                            index++;
                        }


                        try
                        {
                            using (var stream = new FileStream(filePath1, FileMode.Create))
                            {
                                await file.CopyToAsync(stream);
                            }

                            
                        }
                        catch (Exception ex)
                        {
                            // Handle exception
                        }

                        listPhotoName.Add(Path.GetFileName(filePath1));
                    }
                }
            }


            
                _photoService.DeletePhoto(post.PostId);
            
                

            var p = _postService.GetPostById(post.PostId);
            if (p.Caption != post.Caption)
            {
                _postService.UpdatePost(post);
            }
            if (listPhotoName.Count != 0)
            {
                foreach (string photoName in listPhotoName)
                {
                    Photo photo = new Photo();
                    photo.PhotoUrl = "/Image/UploadPic/" + photoName;
                    photo.CreatedAt = DateTime.Now;
                    photo.PostId = post.PostId;
                    _photoService.AddPhoto(photo);
                }
            }


            return RedirectToPage("/Profile");
        }

       
    }
}

Pages/EditProfile.cshtml.cs
using Lombok.NET;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PRN221_Assignment.Models;
using PRN221_Assignment.Services.Interface;
using System.Security.Claims;


namespace PRN221_Assignment.Pages
{
    [Authorize(Roles = "User")]
    [RequiredArgsConstructor]
    public partial class EditProfileModel : PageModel
    {
        private readonly IProfileService _profileService;
        private readonly IUserResolverService userResolverService;

        [BindProperty]
        public User? user { get; set; }

        [BindProperty]
        public string error { get; set; }
        public IActionResult OnGet()
        {
            user = _profileService.GetUserInfo(userResolverService.GetUser());
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(User user, IFormFile profilePhoto)
        {
        
                if (profilePhoto != null && profilePhoto.Length > 0)
                {
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/uploads", profilePhoto.FileName);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await profilePhoto.CopyToAsync(stream);
                    }

                    user.ProfilePhotoUrl = "./uploads/" + profilePhoto.FileName;
                }

                _profileService.EditProfile(user);
                await UpdateUserClaims(user);
            
            return RedirectToPage("/Profile");
        }

        private async Task UpdateUserClaims(User user)
        {
            var claims = new List<Claim>()
            {
                new Claim(ClaimTypes.GivenName, user.Fullname),
                new Claim(ClaimTypes.Name, user.Username),
                new Claim(ClaimTypes.NameIdentifier, user.UserId.ToString()),
                new Claim(ClaimTypes.Email, user.Email),
                new Claim(ClaimTypes.Role, "User"),
                new Claim("UserId", user.UserId.ToString()),
                new Claim("profile_picture", user.ProfilePhotoUrl ?? "./assets/images/user/null.png")
            };

            var identity = new ClaimsIdentity(claims, "Cookies");
            var principal = new ClaimsPrincipal(identity);

            await HttpContext.SignInAsync(principal);
        }

        public IActionResult OnPostUpdatePass(string cpass, string npass, string vpass)
        {
            var userid = userResolverService.GetUser();
            var user = _profileService.GetUserInfo(userResolverService.GetUser());
            if(user.Password != cpass)
            {
                error = "Current password is wrong";
                return Page();
            }
            if(npass != vpass)
            {
				error = "Verify password is not matched";
				return Page();
			}

			user.Password = npass;
			
			_profileService.resetPassword(user);
			user = _profileService.GetUserInfo(userResolverService.GetUser());
			return RedirectToPage("/Profile");
		}
    }

}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PRN221_Assignment.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Login.cshtml.cs
using Lombok.NET;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PRN221_Assignment.Models;
using PRN221_Assignment.Services.Interface;
using System.Security.Claims;

namespace PRN221_Assignment.Pages
{
    [RequiredArgsConstructor]
    public partial class LoginModel : PageModel
    {
        [BindProperty]
        public User user { get; set; } = default!;
        private readonly ILoginService _loginService;
        private readonly ILogger<LoginModel> _logger;
        private readonly IAdminService _adminService;
        private readonly IUserResolverService _userResolver;
        public string error;

        [BindProperty]
        public string ReturnUrl { get; set; }
        public void OnGet(string returnUrl = "Index")
        {
            ReturnUrl = returnUrl;
            HttpContext.SignOutAsync(Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationDefaults.AuthenticationScheme);
        }
        public IActionResult OnPost(string returnUrl)
        {
            var userLogin = _loginService.ExistUser(user.Username, user.Password);
            var blocked = _adminService.GetBlockedAccount();
            bool isBlocked = false;
            error = "Username or password is incorrect!";
            
            if (userLogin != null && !isBlocked)
            {
                List<Claim> listClaim = new List<Claim>()
            {
                new Claim(ClaimTypes.GivenName, userLogin.Fullname),
                new Claim(ClaimTypes.Name, userLogin.Username),
                new Claim(ClaimTypes.NameIdentifier, userLogin.UserId.ToString()),
                new Claim(ClaimTypes.Email, userLogin.Email),
                new Claim("UserId", userLogin.UserId.ToString()),
                new Claim(ClaimTypes.Role, "User"),
                new Claim("profile_picture", userLogin.ProfilePhotoUrl ?? "./assets/images/user/null.png")
            };
                ClaimsIdentity ci = new ClaimsIdentity(listClaim, Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationDefaults.AuthenticationScheme);
                ClaimsPrincipal cp = new ClaimsPrincipal(ci);
                HttpContext.SignInAsync(cp);
                if (blocked.Any(x => x.User1Id == userLogin.UserId))
                {
                    error = "Your account has been disabled";
                    isBlocked = true;
                    return Page();
                }
                if (returnUrl.Equals("/")) returnUrl = "/Index";
                return RedirectToPage(returnUrl);
            }
            
            return Page();
        }
        
        public async Task<IActionResult> OnGetLogout()
        {
            await HttpContext.SignOutAsync(Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToPage("/Login");
        }

        public async Task<IActionResult> OnPostCheckingLock()
        {
            var blocked = _adminService.GetBlockedAccount();
            if (blocked.Any(x => x.User1Id == _userResolver.GetUser()))
            {
                error = "Your account has been disabled";
                await HttpContext.SignOutAsync(Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationDefaults.AuthenticationScheme);
                return new JsonResult(new { success = true, message = error });
            }
            return new JsonResult(new { success = false });

        }
    }
}

Pages/Profile.cshtml.cs
using Lombok.NET;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using PRN221_Assignment.Models;
using PRN221_Assignment.Services;
using PRN221_Assignment.Services.Interface;
using System;
using System.IO;
using System.Text;

namespace PRN221_Assignment.Pages;

[Authorize(Roles = "User")]
[RequiredArgsConstructor]
public partial class Profile : PageModel
{
    private readonly IProfileService _profileService;
    private readonly IUserResolverService _userResolver;
    private readonly IPostService _postService;
    private int? _id;
    [BindProperty(SupportsGet = true)]
    public int Id
    {
        get => _id ?? _userResolver.GetUser();
        set => _id = value;
    }
    public Post post { get; set; }
    public IActionResult OnGet(int postId = 0,int commentId = 0)
    {
        if (Id == 0) return RedirectToPage("/Index");
        ViewData["User"] = _profileService.GetUserInfo(Id);
        ViewData["photos"] = _profileService.GetUserPhoto(Id);
        ViewData["likes"] = _profileService.GetCountNumberLikes(Id);
        ViewData["comments"] = _profileService.GetCountNumberComments(Id);
        var b = _profileService.GetAllFriendOfUser(Id);
        ViewData["friends"] = b;
        var a = _profileService.GetAllFriendRelatetionshipOfUser(_userResolver.GetUser());
        ViewData["userFriends"] = a;
        ViewData["listPost"] = _postService.GetAllPostOfFriendAndFollower(Id);
        ViewData["listSaved"] = _postService.GetAllPostIdsaved();
        ViewData["isFollow"] = _profileService.CheckIsFollow(_userResolver.GetUser(), Id);
        ViewData["following"] = _profileService.GetCountNumberfollowing(Id);
        ViewData["follower"] = _profileService.GetCountNumberFollower(Id);
        if(postId != 0)
        {
            ViewData["postId"] = postId;
        }

        if (commentId != 0)
        {
            ViewData["commentId"] = commentId;
        }
        return Page();
    }

    public IActionResult OnPostFollow(int UserId)
    {
        _profileService.Follow(_userResolver.GetUser(), UserId);
        return new JsonResult("ok");
    }

    public IActionResult OnDeleteFollow(int UserId)
    {
        _profileService.UnFollow(_userResolver.GetUser(), UserId);
        return new JsonResult("ok");
    }
}

Pages/EditPost.cshtml
@page
@using System.Globalization
@using System.Security.Claims
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using PRN221_Assignment.Data
@using PRN221_Assignment.Models
@{
    ViewData["Title"] = "Edit Post";
    var post = (Post)ViewBag.post;
    var photo = (List<Photo>)ViewBag.photo;
}
@model EditPostModel
<div id="content-page" class="content-page">
    <div class="container">
        <div class="row">
            
            <div class="col-lg-12">
                <div class="iq-edit-list-data">
                    <div class="tab-content">
                        <div class="tab-pane fade active show" id="personal-information" role="tabpanel">
                            <div class="card">
                                <div class="card-header d-flex justify-content-between">
                                    <div class="header-title">
                                        <h4 class="card-title">Update post</h4>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <form class="" method="post" enctype="multipart/form-data" id="postForm-update">
                                        <!-- Hidden inputs for storing data -->
                                        
                                        
                                        <div class="d-flex align-items-center">
                                            <div class="user-img">
                                                <img src="@User.FindFirstValue("profile_picture")" alt="userimg" class="avatar-60 rounded-circle img-fluid">
                                            </div>
                                            <div id="caption" class="post-text ms-3 w-100">
                                                <input type="text" class="form-control rounded" placeholder="Write something here..." style="border:none;" value="@post.Caption" asp-for="post.Caption">
                                                <input type="hidden" asp-for="post.PostId" value="@post.PostId">

                                            </div>
                                        </div>
                                        <div id="imagePreview" class="newt">
                                            @if (photo != null)
                                            {
                                                foreach (var p in photo)
                                                {
                                                    <div class="post-image">
                                                        
                                                        <img src="@p.PhotoUrl" class="img-fluid rounded w-100">
                                                        <button type="button" class="delete-btn btn btn-danger btn-sm close-img"><i class="fa fa-close"></i></button>
                                                        
                                                    </div>
                                                }
                                            }
                                        </div>
                                        <hr>
                                        <ul class="d-flex flex-wrap align-items-center list-inline m-0 p-0">
                                            <li class="col-md-6 mb-3">
                                                <div class="bg-soft-primary rounded p-2 pointer me-3" onclick="document.getElementById('fileInput').click()">
                                                    <img src="~/assets/images/small/07.png" alt="icon" class="img-fluid"> Photo
                                                </div>
                                                <input type="file" id="fileInput" style="display: none;" name="listFile" accept="image/*" multiple>
                                            </li>
                                        </ul>
                                        <hr>
                                        <button class="btn btn-primary d-block w-100 mt-3 js-add-slide" id="postButton">Update post</button>
                                        @* <input type="hidden" name="existingPhotoURLs" id="existingPhotoURLs"> *@
                                        <input type="hidden" name="imageNames" id="existingPhoto" value="@string.Join("||", photo.Select(p => p.PhotoUrl))">
                                       @* // <input type="file" id="uploadedFilesInput" name="uploadedFiles" multiple style="display:none;"> *@

                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Pages/EditProfile.cshtml
@page
@using System.Globalization
@using System.Security.Claims
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using PRN221_Assignment.Data
@using PRN221_Assignment.Models
@{ViewData["Title"] = "Edit Profile";}
@model EditProfileModel
<div id="content-page" class="content-page">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body p-0">
                        <div class="iq-edit-list">
                            <ul class="iq-edit-profile row nav nav-pills">
                                <li class="col-md-3 p-0">
                                    <a class="nav-link active" data-bs-toggle="pill" href="#personal-information">
                                        Personal Information
                                    </a>
                                </li>
                                <li class="col-md-3 p-0">
                                    <a class="nav-link" data-bs-toggle="pill" href="#chang-pwd">
                                        Change Password
                                    </a>
                                </li>

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="iq-edit-list-data">
                    <div class="tab-content">
                        <div class="tab-pane fade active show" id="personal-information" role="tabpanel">
                            <div class="card">
                                <div class="card-header d-flex justify-content-between">
                                    <div class="header-title">
                                        <h4 class="card-title">Personal Information</h4>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <form method="post" enctype="multipart/form-data">
                                        <div class="form-group row align-items-center">
                                            <div class="col-md-12">
                                                <div class="profile-img-edit">
                                                    <img class="profile-pic" src="@Model.user.ProfilePhotoUrl" alt="profile-pic">
                                                    <div class="p-image">
                                                        <i class="ri-pencil-line upload-button text-white"></i>
                                                        <input class="file-upload" type="file" accept="image/*" value="@Model.user.ProfilePhotoUrl" name="profilePhoto" />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class=" row align-items-center">
                                            <div class="form-group col-sm-6">
                                                <label for="fname" class="form-label">Full Name:</label>
                                                <input type="text" class="form-control" asp-for="user.Fullname" id="fname" required />
                                            </div>
                                            <div class="form-group col-sm-6">
                                                <label for="uname" class="form-label">Email:</label>
                                                <input type="text" class="form-control" id="uname" asp-for="user.Email" required />
                                            </div>
                                            <div class="form-group col-sm-6">
                                                <label class="form-label d-block">Gender:</label>
                                                <div class="form-check form-check-inline">
                                                    <input class="form-check-input" type="radio" asp-for="user.Gender" id="genderMale" value="1" checked="@(Model.user.Gender == 1)">
                                                    <label class="form-check-label" for="genderMale"> Male</label>
                                                </div>
                                                <div class="form-check form-check-inline">
                                                    <input class="form-check-input" type="radio" asp-for="user.Gender" id="genderFemale" value="0" checked="@(Model.user.Gender == 0)">
                                                    <label class="form-check-label" for="genderFemale"> Female</label>
                                                </div>
                                                <div class="form-check form-check-inline">
                                                    <input class="form-check-input" type="radio" asp-for="user.Gender" id="genderOther" value="3" checked="@(Model.user.Gender > 2)">
                                                    <label class="form-check-label" for="genderOther"> Other</label>
                                                </div>

                                            </div>
                                            <div class="form-group col-sm-6">
                                                <label for="dob" class="form-label">Date Of Birth:</label>
                                                <input type="date" class="form-control" id="dob" asp-for="user.Dob" required>
                                            </div>
                                            <div class="form-group col-sm-12">
                                                <label class="form-label">Bio:</label>
                                                <textarea class="form-control editprofile-address" asp-for="user.Bio" rows="5" style="line-height: 22px;">
                                                </textarea>
                                            </div>
                                        </div>
                                        <input type="hidden"  asp-for="user.UserId">
                                        <input type="hidden"  asp-for="user.Username">
                                        <button type="submit" class="btn btn-primary me-2">Submit</button>
                                        <button onclick="redirectToProfile();" class="btn bg-soft-danger">Cancel</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="chang-pwd" role="tabpanel">
                            <div class="card">
                                <div class="card-header d-flex justify-content-between">
                                    <div class="iq-header-title">
                                        <h4 class="card-title">Change Password</h4>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <form method="post" asp-page-handler="UpdatePass">
                                        @Model.error
                                        <div class="form-group">
                                            <label for="cpass" class="form-label">Current Password:</label>
                                            <a href="#" class="float-end">Forgot Password</a>
                                            <input type="Password" class="form-control" name="cpass" value="">
                                        </div>
                                        <div class="form-group">
                                            <label for="npass" class="form-label">New Password:</label>
                                            <input type="Password" class="form-control" name="npass" value="">
                                        </div>
                                        <div class="form-group">
                                            <label for="vpass" class="form-label">Verify Password:</label>
                                            <input type="Password" class="form-control" name="vpass" value="">
                                        </div>
                                        <button type="submit" class="btn btn-primary me-2">Submit</button>
                                        <button type="reset" class="btn bg-soft-danger">Cancle</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function formatDate(input) {
        let date = new Date(input.value);
        let day = String(date.getDate()).padStart(2, '0');
        let month = String(date.getMonth() + 1).padStart(2, '0'); 
        let year = date.getFullYear();
    }
</script>